### ISSUE TITLE
Exception when selecting "Properties" from Solution Explorer file context menu.

### ISSUE THREAD

**Issue by Dart-Matter** [GeorgRottensteiner/C64Studio#126]
This is from a recent build you provided me to fix a different problem.  Is it maybe not a complete build?

<img width="214" alt="image" src="https://github.com/user-attachments/assets/98394e08-a6d4-4400-a150-4c657441d675">

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.
```
************** Exception Text **************
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "RetroDevStudio.PropCompileTarget.resources" was correctly embedded or linked into assembly "C64Studio" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at RetroDevStudio.PropCompileTarget.InitializeComponent() in D:\projekte\C64Studio\C64Studio\PropertyTabs\PropCompileTarget.Designer.cs:line 174
   at RetroDevStudio.PropCompileTarget..ctor(ProjectElement Element, StudioCore Core) in D:\projekte\C64Studio\C64Studio\PropertyTabs\PropCompileTarget.cs:line 37
   at RetroDevStudio.Dialogs.ElementProperties.AddElementTabs() in D:\projekte\C64Studio\C64Studio\Dialogs\ElementProperties.cs:line 51
   at RetroDevStudio.Dialogs.ElementProperties..ctor(StudioCore Core, ProjectElement Element) in D:\projekte\C64Studio\C64Studio\Dialogs\ElementProperties.cs:line 26
   at RetroDevStudio.Documents.SolutionExplorer.treeElementProperties_Click(Object sender, EventArgs e) in D:\projekte\C64Studio\C64Studio\Documents\SolutionExplorer.cs:line 1337
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9256.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
C64Studio
    Assembly Version: 7.8.28.0
    Win32 Version: 7.8.28
    CodeBase: file:///C:/Program%20Files%20(x86)/C64%20Studio/net4.8/C64Studio.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 1.0.0.0
    Win32 Version: 3.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/C64%20Studio/net4.8/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2005
    Assembly Version: 1.0.0.0
    Win32 Version: 3.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/C64%20Studio/net4.8/WeifenLuo.WinFormsUI.Docking.ThemeVS2005.DLL
----------------------------------------
HexBox
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/C64%20Studio/net4.8/HexBox.DLL
----------------------------------------
FastColoredTextBox
    Assembly Version: 2.16.11.0
    Win32 Version: 2.16.11.0
    CodeBase: file:///C:/Program%20Files%20(x86)/C64%20Studio/net4.8/FastColoredTextBox.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
SourceControl
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/C64%20Studio/net4.8/SourceControl.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by GeorgRottensteiner** [comment]
That looks exactly like one bug I already fixed. For some reason two resource images got missing (the reason is probably me), but I've readded them recently.

Can you recheck with the latest WIP build from https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip

A short note of warning: I'm currently rearranging the breakpoint code, there might be some issues lurking in regards to them.

**Comment by Dart-Matter** [comment]
Confirmed, no crash now. 
Also confirmed, I have never had the breakpoints behave predictably yet.
