### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by mrj001** [GeorgRottensteiner/C64Studio#48]
I was working in a branch, based off commit 74823b7.  This branch was my work on Issue #45, but you've completed that, so I'll remove this branch.  

I do not think the changes I made (2 commits) in my branch caused this as I don't see anything in this stack trace that I touched.  So I'll report it with the above disclosure.

I got a message box with the following in it:

> System.ArgumentOutOfRangeException: InvalidArgument=Value of '2' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListViewItem.ListViewSubItemCollection.get_Item(Int32 index)
   at C64Studio.DebugWatch.UpdateValue(String WatchVar, Boolean IndexedX, Boolean IndexedY, ByteBuffer Data) in C:\Users\mrj00\source\repos\C64Studio\C64Studio\Documents\DebugWatch.cs:line 161
   at C64Studio.DebugWatch.watchReadFromMemoryToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Users\mrj00\source\repos\C64Studio\C64Studio\Documents\DebugWatch.cs:line 324
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at C64Studio.Program.Main(String[] args) in C:\Users\mrj00\source\repos\C64Studio\C64Studio\Program.cs:line 30

**Comment by GeorgRottensteiner** [comment]
Ah, that's a different issue alltogether. It looks like there was a way to add items in the debug watch without 3rd column. That ought to be fixed with commit 370cc4a5.

Thanks for your support, and sorry about making your branch/work obsolete!
